### ISSUE TITLE
[SELF HOSTED] MINIO - Problem with "non-conventionnal" Region

### ISSUE THREAD

**Issue by Gsyltc** [gristlabs/grist-core#1058]
Hi,

I try to use MINIO with my self hosted installation.
The container does not want to start because there is an error with the connection header to the minio server.

`S3Error: **The authorization header is malformed; the region is wrong; expecting 'ca-ctr'.**
    at parseError (/grist/node_modules/minio/dist/main/internal/xml-parser.js:47:13)
    at Object.parseResponseError (/grist/node_modules/minio/dist/main/internal/xml-parser.js:94:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (/grist/node_modules/minio/dist/main/internal/client.js:491:19)
    at async Client.getBucketVersioning (/grist/node_modules/minio/dist/main/internal/client.js:1826:21)
    at async MinIOExternalStorage.hasVersioning (/grist/_build/app/server/lib/MinIOExternalStorage.js:98:28)
    at async checkMinIOBucket (/grist/_build/app/server/lib/configureMinIOExternalStorage.js:76:10)
    at async Object.checkBackend (/grist/_build/app/server/lib/ICreate.js:59:21)
    at async FlexServer.addDoc (/grist/_build/app/server/lib/FlexServer.js:1259:13)
    at async main (/grist/_build/app/server/mergedServerMain.js:143:13)
    at async main (/grist/_build/stubs/app/server/server.js:143:20) {
  code: 'AuthorizationHeaderMalformed',
  bucketname: 'grist',
  resource: '/grist',
  region: 'ca-ctr',
  requestid: 'HIDDEN',
  hostid: 'HIDDEN',
  amzRequestid: 'HIDDEN',
  amzId2: 'HIDDEN',
  amzBucketRegion: 'ca-ctr'`

Grist Version : core v1.1.15
Minio Version : RELEASE.2024-04-18T19-09-19Z
Docker Version : 26.1.4

Thanks

**Comment by fflorent** [comment]
Have you tried setting `GRIST_DOCS_MINIO_BUCKET_REGION="ca-ctr"`?

**Comment by Gsyltc** [comment]
Hi, 

I just found the variable in the code. everything is OK.
If I may make a suggestion, perhaps this variable should be added to the documentation 

Thanks

**Comment by fflorent** [comment]
Indeed! I proposed a PR to document the missing variables.
