### ISSUE TITLE
Error: Cannot find module 'connect-redis'

### ISSUE THREAD

**Issue by leon1995** [gristlabs/grist-core#128]
I just fired up grist using redis, but when I specify `REDIS_URL` then I get the following error
```
grist_1  | yarn run v1.22.17
grist_1  | $ NODE_PATH=_build:_build/stubs node _build/stubs/app/server/server.js
grist_1  | Welcome to Grist.
grist_1  | In quiet mode, see http://localhost:8484 to use.
grist_1  | For full logs, re-run with DEBUG=1
grist_1  | Error: Cannot find module 'connect-redis'
grist_1  | Require stack:
grist_1  | - /_build/app/server/lib/gristSessions.js
grist_1  | - /_build/app/server/lib/Authorizer.js
grist_1  | - /_build/app/gen-server/ApiServer.js
grist_1  | - /_build/app/server/lib/FlexServer.js
grist_1  | - /_build/app/server/mergedServerMain.js
grist_1  | - /_build/stubs/app/server/server.js
grist_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
grist_1  |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
grist_1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
grist_1  |     at require (internal/modules/cjs/helpers.js:101:18)
grist_1  |     at createSessionStoreFactory (/_build/app/server/lib/gristSessions.js:25:28)
grist_1  |     at Object.initGristSessions (/_build/app/server/lib/gristSessions.js:78:33)
grist_1  |     at FlexServer.addSessions (/_build/app/server/lib/FlexServer.js:569:79)
grist_1  |     at Object.<anonymous> (/_build/app/server/mergedServerMain.js:83:20)
grist_1  |     at Generator.next (<anonymous>)
grist_1  |     at fulfilled (/_build/app/server/mergedServerMain.js:11:58) {
grist_1  |   code: 'MODULE_NOT_FOUND',
grist_1  |   requireStack: [
grist_1  |     '/_build/app/server/lib/gristSessions.js',
grist_1  |     '/_build/app/server/lib/Authorizer.js',
grist_1  |     '/_build/app/gen-server/ApiServer.js',
grist_1  |     '/_build/app/server/lib/FlexServer.js',
grist_1  |     '/_build/app/server/mergedServerMain.js',
grist_1  |     '/_build/stubs/app/server/server.js'
grist_1  |   ]
grist_1  | }
```

**Comment by paulfitz** [comment]
Sorry about that! We need to add connect-redis@3.4.0 as an optional dependency. Does:
```
yarn add connect-redis@3.4.0
```
get you going?

**Comment by paulfitz** [comment]
@dugite-code yes that is one way to do it. What kind of build errors are you getting?

I'm going to go ahead and bundle `connect-redis` so in future this will be simpler https://github.com/gristlabs/grist-core/pull/183 - it is a small self-contained library.

**Comment by dugite-code** [comment]
FYI since #183 this is fixed for me

**Comment by paulfitz** [comment]
Thanks for confirming @dugite-code !
