### ISSUE TITLE
ARM support would be nice

### ISSUE THREAD

**Issue by arminus** [gristlabs/grist-core#143]
As it is, the Docker image can't be built on ARM:

```
error /node_modules/chromedriver: Command failed. Exit code: 1 
Command: node install.js 
Arguments: 
Directory: /node_modules/chromedriver 
Output: Only Linux 64 bits supported.
```

I tried installing chromium-driver before the yarn install command in the Dockerfile, but apparently, that driver doesn't get recognized.

**Comment by paulfitz** [comment]
I think @georgegevoian may be looking into ARM support now.

Hmm, chromedriver isn't actually needed to build, only to run tests, so there's no need to have it in the Docker image. Maybe you could try removing `mocha-webdriver` from package.json?

**Comment by arminus** [comment]
That get's me one step further:

```
make: Entering directory '/node_modules/@gristlabs/sqlite3/build'
make: *** No rule to make target 'Release/obj.target/nothing/../../../../../node-addon-api/src/nothing.o', needed by 'Release/obj.target/../../../../../node-addon-api/src/nothing.a'.  Stop.
make: Leaving directory '/node_modules/@gristlabs/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.10.92-v8+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--module=/node_modules/@gristlabs/sqlite3/lib/binding/napi-v3-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/node_modules/@gristlabs/sqlite3/lib/binding/napi-v3-linux-arm" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /node_modules/@gristlabs/sqlite3
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/node_modules/@gristlabs/sqlite3/lib/binding/napi-v3-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/node_modules/@gristlabs/sqlite3/lib/binding/napi-v3-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Linux 5.10.92-v8+
node-pre-gyp ERR! command "/usr/local/bin/node" "/node_modules/@gristlabs/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--build-from-source"
node-pre-gyp ERR! cwd /node_modules/@gristlabs/sqlite3
node-pre-gyp ERR! node -v v14.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/node_modules/@gristlabs/sqlite3/lib/binding/napi-v3-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/node_modules/@gristlabs/sqlite3/lib/binding/napi-v3-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
```

**Comment by robinMcA** [comment]
I got the muti-arch build to work with the docker file here: https://github.com/robinMcA/grist-core/tree/feat/arm-support.
I have had it running in a pi k3s Kubernetes cluster, too

**Comment by paulfitz** [comment]
Thanks for posting that @robinMcA! Do you know what needed all the Qt libraries?

**Comment by robinMcA** [comment]
Hi @paulfitz, `lxml` for python didn't install without them 
got error like 👇🏽 , I did test if all of the libs were needed was just happy that it worked.
```
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-aarch64-2.7/src/lxml/etree.o -w
#32 59.74     src/lxml/etree.c:97:10: fatal error: Python.h: No such file or directory
#32 59.74      #include "Python.h"
#32 59.74               ^~~~~~~~~~
#32 59.74     compilation terminated.
#32 59.74     Compile failed: command 'aarch64-linux-gnu-gcc' failed with exit status 1
#32 59.74     creating tmp
#32 59.74     cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitme5njH.c -o tmp/xmlXPathInitme5njH.o
#32 59.74     /tmp/xmlXPathInitme5njH.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
#32 59.74      main (int argc, char **argv) {
#32 59.74      ^~~~
#32 59.74     cc tmp/xmlXPathInitme5njH.o -lxml2 -o a.out
#32 59.74     error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
```

**Comment by georgegevoian** [comment]
As of version 0.7.8, arm64 support is now included in our official images.

https://hub.docker.com/r/gristlabs/grist/tags
