### ISSUE TITLE
Grist Not start when specify TYPEORM_TYPE to postgres

### ISSUE THREAD

**Issue by syji35** [gristlabs/grist-core#307]
I'm using Grist in version 0.7.9 with docker.  

I configure the TYPEORM to postgres (as explain [here](https://support.getgrist.com/self-managed/#what-is-a-home-database)), but I get an error on startup 👍 
```
Welcome to Grist.
DriverPackageNotInstalledError: Postgres package has not been found installed. Try to install it: npm install pg --save
    at new DriverPackageNotInstalledError (/grist/node_modules/typeorm/error/DriverPackageNotInstalledError.js:10:28)
    at PostgresDriver.loadDependencies (/grist/node_modules/typeorm/driver/postgres/PostgresDriver.js:846:19)
    at new PostgresDriver (/grist/node_modules/typeorm/driver/postgres/PostgresDriver.js:196:14)
    at DriverFactory.create (/grist/node_modules/typeorm/driver/DriverFactory.js:31:24)
    at new Connection (/grist/node_modules/typeorm/connection/Connection.js:52:59)
    at ConnectionManager.create (/grist/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at Object.<anonymous> (/grist/node_modules/typeorm/index.js:198:66)
    at step (/grist/node_modules/tslib/tslib.js:141:27)
    at Object.next (/grist/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/grist/node_modules/tslib/tslib.js:112:62)
```

Here my docker compose file :  

```
services:
  grist:
    image: gristlabs/grist:0.7.9
    environment:
      TYPEORM_TYPE: postgres
      TYPEORM_DATABASE: grist
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: xxxxxxxxx
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      DEBUG: 1
      GRIST_SESSION_SECRET: invent-a-secret-here
      APP_HOME_URL: "https://grist.xxxxx"
      GRIST_SANDBOX_FLAVOR: gvisor
    deploy:
```

**Comment by syji35** [comment]
Thanks @paulfitz. That works

**Comment by helmut72** [comment]
> The tagged version is from 5 months ago

I don't have this problem because I don't use Postgres, but thanks for tagging a new version, 1.0.3. I have also used 0.7.9 until now on my productive system, because `:latest` feels a bit like a developer version.
