### ISSUE TITLE
Websocket behind reverse proxy always has new clientId / wrong userId

### ISSUE THREAD

**Issue by rtgoodwin** [gristlabs/grist-core#440]
Self hosted, behind nginx proxy HTTPS->HTTP, following config:

```
sudo docker run -p 80:80  
 -e GRIST_LOG_LEVEL=debug    
 -e PORT=80
 -e APP_HOME_URL=https://mydomain.com
 -e APP_STATIC_URL=https://mydomain.com   
 -e HOME_PORT=share
 -e GRIST_DOMAIN=mydomain.com
 -e GRIST_SUPPORT_EMAIL=myfowardauthemail 
 -e DEBUG=1
 -e GRIST_PROXY_AUTH_HEADER=myfowardauthemailheader
 -e GRIST_FORWARD_AUTH_HEADER=myfowardauthemailheader
 -e GRIST_IGNORE_SESSION=true 
 -e GRIST_ALLOWED_HOSTS='mydomain.com' 
 -v /home/mydir/persist:/persist:z  
 -e GRIST_SINGLE_ORG=myorg
-it gristlabs/grist:latest
```
The proxy send the Upgrade, Connection Upgrade, and Host headers. 

I am signed in automatically via the browser, but creating or attemping to view a doc results in 'No view access'. Looking at the log, I see my userId=5 for general operations, but the websocket coming in says:
`Client responding to #0 ERROR No view access userId=1, org=myorg, clientId=5fe391985a8aa5cc, counter=4`
`DocManager.openDoc Authorizer key { urlId: 'cGJVmbQbdS5h8RYc8Xu97P', userId: 1, org: 'myorg' }`

There is a `grist_core` cookie set to the domain as `.mydomain.com`. After deleting the sessions db and just visiting the home and opening a doc results in this entry:
`g-wgw4r4Y3tfQnTVZrdvAiGB|1677424972578.0|{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"domain":"mydomain.com","path":"/","sameSite":"lax"},"alive":1}`

Here's a bit of the logging that happens in this scenario:
```
/cGJVmbQbdS5h/Untitled-document, language=en-US, platform=MacIntel, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36, org=myorg, email=myforwardauthemail, userId=5, altSessionId=undefined
2023-02-25 15:15:46.315 - debug: Auth[GET]: mydomain.com /session/access/active customHostSession=, method=GET, host=mydomain.com, path=/session/access/active, org=myorg, email=myforwardauthemail, userId=5, altSessionId=undefined
2023-02-25 15:15:46.321 - debug: Auth[GET]: mydomain.com /session/access/all customHostSession=, method=GET, host=mydomain.com, path=/session/access/all, org=myorg, email=myforwardauthemail, userId=5, altSessionId=undefined
2023-02-25 15:15:46.329 - debug: Auth[GET]: mydomain.com /worker/cGJVmbQbdS5h8RYc8Xu97P customHostSession=, method=GET, host=mydomain.com, path=/worker/cGJVmbQbdS5h8RYc8Xu97P, org=myorg, email=myforwardauthemail, userId=5, altSessionId=undefined
2023-02-25 15:15:46.471 - debug: Auth[GET]: mydomain.com /docs/cGJVmbQbdS5h customHostSession=, method=GET, host=mydomain.com, path=/docs/cGJVmbQbdS5h, org=myorg, email=myforwardauthemail, userId=5, altSessionId=undefined
2023-02-25 15:15:46.611 - info: Comm: Got Websocket connection userId=1, org=myorg, clientId=e31d34222d3a0cc4, counter=2, urlPath=/?clientId=e31d34222d3a0cc4&counter=3&newClient=1&browserSettings=%7B%22timezone%22%3A%22America%2FChicago%22%7D&user=myforwardauthemail, reuseClient=true
2023-02-25 15:15:46.612 - debug: Client sending clientConnect newClient=true, needReload=false, docsClosed=0, missedMessages=undefined, org=myorg, clientId=e31d34222d3a0cc4, counter=3
2023-02-25 15:15:46.673 - info: Client onMessage '{"reqId":0,"method":"openDoc","args":["cGJVmbQbdS5h8RYc8Xu97P","default",null]}' org=myorg, clientId=e31d34222d3a0cc4, counter=3
2023-02-25 15:15:46.674 - debug: DocManager.openDoc Authorizer key { urlId: 'cGJVmbQbdS5h8RYc8Xu97P', userId: 1, org: 'myorg' }
2023-02-25 15:15:46.674 - warn: Client Responding to method openDoc with error: ErrorWithCode: No view access
    at assertAccess (/grist/_build/app/server/lib/Authorizer.js:540:19)
    at DocManager.openDoc (/grist/_build/app/server/lib/DocManager.js:265:43)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client._onMessage (/grist/_build/app/server/lib/Client.js:435:58) {
  code: 'AUTH_NO_VIEW',
  details: [Object]
} AUTH_NO_VIEW userId=1, org=myorg, clientId=e31d34222d3a0cc4, counter=3
```

Logically it seems like the websocket session (or cookie?) isn't being ignored, or is being ignored and tagged as a new session. Not sure how to solve this; I suppose if I could pass an upstream session as a header, but I kind of thought the point of "IGNORE_SESSION" was to avoid this. 

Verrrry close to this finally working, so fingers crossed!

**Comment by rtgoodwin** [comment]
Actually solved this, didn't realize the FORWARD_AUTH_HEADER wasn't being sent on that resource path (/dw). Swimming now! :)

**Comment by paulfitz** [comment]
Glad you found a fix @rtgoodwin
