### ISSUE TITLE
Impossible to import grist file when using Minio storage

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#544]
Steps to reproduce:

1. Run Minio through podman or docker locally: 
```
podman run -p 9000:9000 -p 9001:9001 --name minio -v $HOME/tmp/minio-data:/data \
           quay.io/minio/minio server /data --console-address ":9001"
```
2. Configure a user access through the Minio console with credentials `devuser`/`devpasswd`: https://localhost:9001
3. Create a bucket named dev-versinoning (with versioning support)
4. Back to a shell, source the following `.env` file:
```env
GRIST_DOCS_MINIO_BUCKET="dev-versioning"
GRIST_DOCS_MINIO_PREFIX="grist-dev"
GRIST_DOCS_MINIO_ENDPOINT="localhost"
GRIST_DOCS_MINIO_PORT="9000"
GRIST_DOCS_MINIO_USE_SSL=0
GRIST_DOCS_MINIO_ACCESS_KEY="devuser"
GRIST_DOCS_MINIO_SECRET_KEY="devpasswd"
```
5. Run: `yarn start`
6. unzip the attached document to extract the grist file (or get any grist file, this would much certainly work as well): [doc.zip](https://github.com/gristlabs/grist-core/files/11829616/doc.zip)
7. Open Grist, go to some workspace and import the attached grist document
    ⇒ You get this error:
```
Error accessing document
You can try reloading the document, or using recovery mode. Recovery mode opens the document to be fully accessible to owners, and inaccessible to others. It also disables formulas. [NO_METADATA_ERROR: 5URWwHK9ffhihD6k9DUK8R has no metadata]
```
8. Back in your shell stop the server, run this command to store the document in the filesystem: `export GRIST_DOCS_MINIO_BUCKET=""`
9. Run steps 5 to 7 anew, the import should work as expected now.

**Comment by fflorent** [comment]
The error reported in the UI makes me think of #359 

Here are the log extract:
```
22023-06-22 08:38:48.534 - debug: Auth[GET]: localhost:8484 /worker/import customHostSession=, method=GET, host=localhost:8484, path=/worker/import, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:48.560 - debug: Auth[POST]: localhost:8484 /uploads customHostSession=, method=POST, host=localhost:8484, path=/uploads, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:48.563 - debug: Prepared to receive upload into tmp dir /tmp/grist-upload-30665QfLBN99rClTA org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:48.646 - debug: Received file Untitled document.grist (22237184 bytes) org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:48.649 - debug: Created uploadId 0 in tmp dir /tmp/grist-upload-30665QfLBN99rClTA org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:48.663 - debug: Auth[POST]: localhost:8484 /workspaces/3/import customHostSession=, method=POST, host=localhost:8484, path=/workspaces/3/import, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:48.708 - debug: DocManager._createNewDoc picked name dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:48.749 - debug: backupSqliteDatabase: starting copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:48.841 - info: backupSqliteDatabase: copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) completed successfully docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:48.841 - debug: backupSqliteDatabase: stopped copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) docId=dWKbRaDzAhXweExdbkjj41, maxStepTimeMs=13, numSteps=6
2023-06-22 08:38:48.887 - info: HostedStorageManager Local hash does not match redis: 71367bce54bfa9fdc58381e4a4806198 vs unknown docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:48.904 - debug: UploadSet: cleaning up uploadId 0
2023-06-22 08:38:48.937 - debug: Auth[GET]: localhost:8484 /docs/dWKbRaDzAhXweExdbkjj41 customHostSession=, method=GET, host=localhost:8484, path=/docs/dWKbRaDzAhXweExdbkjj41, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:48.968 - debug: Auth[GET]: localhost:8484 /dWKbRaDzAhXw/Untitled-document customHostSession=, method=GET, host=localhost:8484, path=/dWKbRaDzAhXw/Untitled-document, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:49.126 - debug: Auth[GET]: localhost:8484 /session/access/active customHostSession=, method=GET, host=localhost:8484, path=/session/access/active, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:49.132 - debug: Auth[GET]: localhost:8484 /session/access/all customHostSession=, method=GET, host=localhost:8484, path=/session/access/all, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:49.165 - debug: Auth[GET]: localhost:8484 /worker/dWKbRaDzAhXweExdbkjj41 customHostSession=, method=GET, host=localhost:8484, path=/worker/dWKbRaDzAhXweExdbkjj41, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:49.190 - debug: Auth[GET]: localhost:8484 /docs/dWKbRaDzAhXw customHostSession=, method=GET, host=localhost:8484, path=/docs/dWKbRaDzAhXw, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:49.229 - info: Comm: Got Websocket connection clientId=8cb465f5b9efee56, counter=null, urlPath=/?clientId=0&counter=8&newClient=1&browserSettings=%7B%22timezone%22%3A%22Europe%2FParis%22%7D&user=you%40example.com, reuseClient=false
2023-06-22 08:38:49.229 - debug: Client sending clientConnect newClient=true, needReload=false, docsClosed=0, missedMessages=undefined, email=you@example.com, org=docs, altSessionId=rn1qHZwrGVyEdX7hLuzije, clientId=8cb465f5b9efee56, counter=8
2023-06-22 08:38:49.239 - info: Client onMessage '{"reqId":0,"method":"openDoc","args":["dWKbRaDzAhXweExdbkjj41","default",null]}' email=you@example.com, org=docs, altSessionId=rn1qHZwrGVyEdX7hLuzije, clientId=8cb465f5b9efee56, counter=8
2023-06-22 08:38:49.241 - debug: DocManager.openDoc Authorizer key { urlId: 'dWKbRaDzAhXweExdbkjj41', userId: 5, org: 'docs' }
2023-06-22 08:38:49.242 - debug: DocManager.fetchDoc dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:49.252 - debug: ActiveDoc loadDoc access=owners, userId=5, email=you@example.com, age=22, org=docs, altSessionId=rn1qHZwrGVyEdX7hLuzije, clientId=8cb465f5b9efee56, counter=8, docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:49.252 - info: HostedStorageManager waiting for document to finish docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:49.254 - debug: backupSqliteDatabase: starting copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:49.259 - info: backupSqliteDatabase: copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) completed successfully docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:49.259 - debug: backupSqliteDatabase: stopped copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) docId=dWKbRaDzAhXweExdbkjj41, maxStepTimeMs=0, numSteps=1
2023-06-22 08:38:49.271 - info: ext doc upload: minio://dev-versioning/grist-dev/dWKbRaDzAhXweExdbkjj41.grist checksum 2fd4d684b99f2c687c9fc524f6c5434e version 3bf14c62-03e0-4aaf-a6c1-b0ca318270af
2023-06-22 08:38:49.295 - info: ext meta upload: minio://dev-versioning/grist-dev/assets/unversioned/dWKbRaDzAhXweExdbkjj41/meta.json checksum 3be70e0ccc0ac4b92010acceb11885d2 version 076b81f5-c957-40b3-bc76-b6c544a9d54a
2023-06-22 08:38:49.300 - info: Pruned 0 versions of 1 for document dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.296 - debug: backupSqliteDatabase: starting copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.299 - info: backupSqliteDatabase: copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) completed successfully docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.300 - debug: backupSqliteDatabase: stopped copy of /home/florentpro/projects/grist-core/docs/dWKbRaDzAhXweExdbkjj41.grist (backup) docId=dWKbRaDzAhXweExdbkjj41, maxStepTimeMs=1, numSteps=1
2023-06-22 08:38:50.301 - info: HostedStorageManager Local hash does not match redis: 2fd4d684b99f2c687c9fc524f6c5434e vs unknown docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.320 - info: ext doc download: dWKbRaDzAhXweExdbkjj41 with checksum 2fd4d684b99f2c687c9fc524f6c5434e and version 3bf14c62-03e0-4aaf-a6c1-b0ca318270af
2023-06-22 08:38:50.330 - debug: DB dWKbRaDzAhXweExdbkjj41 open successfully
table names [
  '_gristsys_Files',
  '_gristsys_Action',
  '_gristsys_Action_step',
  '_gristsys_ActionHistory',
  '_gristsys_ActionHistoryBranch',
  '_gristsys_FileInfo',
  '_gristsys_PluginData'
]
2023-06-22 08:38:50.333 - error: ActiveDoc Failed to load document [OperationalError: SQLITE_ERROR: no such table: _grist_Tables_column] {
  cause: [Error: SQLITE_ERROR: no such table: _grist_Tables_column] {
    errno: 1,
    code: 'NO_METADATA_ERROR'
  },
  isOperational: true,
  errno: 1,
  code: 'SQLITE_ERROR'
} access=owners, userId=5, email=you@example.com, age=22, org=docs, altSessionId=rn1qHZwrGVyEdX7hLuzije, clientId=8cb465f5b9efee56, counter=8, docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.333 - debug: ActiveDoc shutdown starting access=owners, docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.334 - error: ActiveDoc Failed to remove expired attachments [OperationalError: SQLITE_ERROR: no such table: _grist_Attachments] {
  cause: [Error: SQLITE_ERROR: no such table: _grist_Attachments] {
    errno: 1,
    code: 'SQLITE_ERROR'
  },
  isOperational: true,
  errno: 1,
  code: 'SQLITE_ERROR'
} access=owners, docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.335 - debug: DocPluginManager.shutdown cleaning up 1 plugins
2023-06-22 08:38:50.337 - debug: DocStorage shutdown success
2023-06-22 08:38:50.337 - debug: DocPluginManager.shutdown removing tmpDir /tmp/grist-tmp-30665e5SvSo73DucG
2023-06-22 08:38:50.338 - error: ActiveDoc failed to shutdown granular access TypeError: Cannot read properties of undefined (reading 'close')
    at ActiveDoc._doShutdownImpl (/home/florentpro/projects/grist-core/_build/app/server/lib/ActiveDoc.js:1737:40)
    at async ActiveDoc.shutdown (/home/florentpro/projects/grist-core/_build/app/server/lib/ActiveDoc.js:396:9)
    at async ActiveDoc.loadDoc (/home/florentpro/projects/grist-core/_build/app/server/lib/ActiveDoc.js:480:13)
    at async InactivityTimer.disableUntilFinish (/home/florentpro/projects/grist-core/_build/app/common/InactivityTimer.js:76:20) access=owners, docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.338 - debug: ActiveDoc shutdown complete access=owners, docId=dWKbRaDzAhXweExdbkjj41
2023-06-22 08:38:50.338 - warn: Client Responding to method openDoc with error: Error: SQLITE_ERROR: no such table: _grist_Tables_column SQLITE_ERROR email=you@example.com, userId=5, age=22, org=docs, altSessionId=rn1qHZwrGVyEdX7hLuzije, clientId=8cb465f5b9efee56, counter=8
2023-06-22 08:38:50.338 - warn: Client responding to #0 ERROR NO_METADATA_ERROR: dWKbRaDzAhXweExdbkjj41 has no metadata email=you@example.com, userId=5, age=22, org=docs, altSessionId=rn1qHZwrGVyEdX7hLuzije, clientId=8cb465f5b9efee56, counter=8
2023-06-22 08:38:50.341 - info: Client websocket closed; will discard client in 300 sec email=you@example.com, userId=5, age=22, org=docs, altSessionId=rn1qHZwrGVyEdX7hLuzije, clientId=8cb465f5b9efee56, counter=8
2023-06-22 08:38:50.350 - debug: Auth[POST]: localhost:8484 /log customHostSession=, method=POST, host=localhost:8484, path=/log, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
2023-06-22 08:38:50.351 - warn: client error fileName=http://localhost:8484/v/unknown/main.bundle.js, lineNumber=734, columnNumber=25, message=NO_METADATA_ERROR: dWKbRaDzAhXweExdbkjj41 has no metadata, code=SQLITE_ERROR, docId=dWKbRaDzAhXweExdbkjj41, page=http://localhost:8484/o/docs/dWKbRaDzAhXw/Untitled-document, language=fr, platform=Linux x86_64, userAgent=Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0, org=docs, email=you@example.com, userId=5, altSessionId=rn1qHZwrGVyEdX7hLuzije
```

**Comment by paulfitz** [comment]
Thanks for the detailed report @fflorent, I'll look into it. It looks like some confusion over when to actually initialize the document. Have you tried running with Redis available? The main tests for external storage are in https://github.com/gristlabs/grist-core/blob/main/test/server/lib/HostedStorageManager.ts and it may be that we always have Redis available when running those tests. Redis used to be necessary (when S3 had fewer consistency guarantees). There could easily be some entanglement that either needs documenting or stripping out.

**Comment by fflorent** [comment]
I see. So I may try to mount a Redis instance locally and see whether the document import runs. If it does, maybe we should fail the server startup (which could be made along with issue #545).

**Comment by fflorent** [comment]
I cannot reproduce it anymore, unfortunately. I am closing the issue (I may reopen it later if I encounter the issue anew).
