### ISSUE TITLE
[docker]error->UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by TaoChan1005** [gristlabs/grist-core#633]
It doesn't work.

```bash
grist  | 2023-08-19 19:38:09.431 - debug: Auth[GET]: localhost:8484 / customHostSession=, method=GET, host=localhost:8484, path=/, org=, email=anon@getgrist.com, userId=1, altSessionId=undefined
grist  | (node:124) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'alive' of undefined
grist  |     at forceSessionChange (/grist/_build/app/server/lib/BrowserSession.js:12:36)
grist  |     at /grist/_build/app/server/lib/Authorizer.js:419:49
grist  |     at Layer.handle [as handle_request] (/grist/node_modules/express/lib/router/layer.js:95:5)
grist  |     at next (/grist/node_modules/express/lib/router/route.js:137:13)
grist  |     at noop (/grist/_build/app/server/lib/FlexServer.js:99:34)
grist  |     at Layer.handle [as handle_request] (/grist/node_modules/express/lib/router/layer.js:95:5)
grist  |     at next (/grist/node_modules/express/lib/router/route.js:137:13)
grist  |     at addRequestUser (/grist/_build/app/server/lib/Authorizer.js:381:12)
grist  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
grist  |     at async /grist/_build/app/server/lib/expressWrap.js:14:13
grist  | (Use `node --trace-warnings ...` to show where the warning was created)
grist  | (node:124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
grist  | (node:124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TaoChan1005** [comment]
`REDIS_URL` is setted wrong. `REDIS_URL=redis://:PASSWD@redis:6379/3`

**Comment by paulfitz** [comment]
Glad you figured it out @TaoChan1005, and thanks for reporting what worked.
