### ISSUE TITLE
Listening on IPv6

### ISSUE THREAD

**Issue by AndreKR** [gristlabs/grist-core#644]
Most of my servers don't have IPv4 addresses anymore. (Docker still maintains a Docker-internal IPv4 network, but it isn't routed to the internet.)

The  Grist Dockerfile sets `GRIST_HOST=0.0.0.0` which on Linux means "all IPv4 addresses", so Grist is unreachable. (A Docker exposed port only does IPv6->IPv6 or IPv4->IPv4.)

I tried setting GRIST_HOST to `::`, which *kind of* worked: the web server was reachable and I got an error message in the browser:
```
TypeError [ERR_INVALID_URL]: Invalid URL: http://:::8484
    at new NodeError (internal/errors.js:322:7)
    at onParseError (internal/url.js:270:9)
    at new URL (internal/url.js:346:5)
    at new URL (internal/url.js:343:22)
    at FlexServer.getHomeUrl (/grist/_build/app/server/lib/FlexServer.js:225:25)
    at FlexServer._sendAppPage (/grist/_build/app/server/lib/sendAppPage.js:77:69)
    at /grist/_build/app/server/lib/FlexServer.js:1268:28
    at Layer.handle_error (/grist/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/grist/node_modules/express/lib/router/index.js:315:13)
    at /grist/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/grist/node_modules/express/lib/router/index.js:335:12)
    at next (/grist/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/grist/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/grist/node_modules/express/lib/router/index.js:315:13)
    at /grist/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/grist/node_modules/express/lib/router/index.js:335:12)
```

I also tried setting GRIST_HOST to `[::]`, but I got an error message in the log:
```
2023-08-24 20:17:49.799 - info: == Grist version is 1.1.3 (commit unknown)
2023-08-24 20:17:49.820 - debug: skipping incomplete language fa (set GRIST_OFFER_ALL_LANGUAGES if you want it)
2023-08-24 20:17:49.851 - info: Loading empty config because /persist/config.json missing
2023-08-24 20:17:49.866 - warn: did not find an appropriately named example workspace in deployment
2023-08-24 20:17:49.870 - info: No plugins directory: ENOENT: no such file or directory, scandir '/grist/.grist/plugi                                                                                                                        ns'
2023-08-24 20:17:49.886 - info: Found 1 valid plugins on the system
2023-08-24 20:17:49.887 - debug: PLUGIN builtIn/core -- /grist/plugins/core
2023-08-24 20:17:49.899 - info: Server timeouts: keepAliveTimeout 305000 headersTimeout 306000
Error: getaddrinfo ENOTFOUND [::]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[::]'
}
```

**Comment by arcandspark** [comment]
I ran into this attempting to deploy into a single-stack IPv6 environment. I was able to work around it and did some digging info a few issues I found while attempting to get it working.

There are four environment variables that need to be set to get Grist up and running and listening on the IPv6 wildcard address:

```
GRIST_HOST=::
GRIST_UNTRUSTED_PORT=8485
APP_UNTRUSTED_URL=http://<dns-fqdn>:8485
APP_HOME_URL=http://<dns-fqdn>:8484
```
Ports can be changed to anything valid. URLs **must** use a DNS FQDN for the host part, IPv6 literals will cause various other errors in Grist.

*All line numbers below are from commit `efd8751b`*

The value of `GRIST_HOST` is passed directly to server.listen() at FlexServer.ts:2175 and controls the socket listen address for the HTTP server. However, the value of `GRIST_HOST` is used elsewhere in problematic ways.

Ultimately the concerns of the socket bind address and URL generation should be separated. Some URL generation with IPv4 literals like `0.0.0.0` result in valid but nonsensical URLs like `http://0.0.0.0:8484`. Values like this cannot be used by a client, but the application still functions, so any part of the code that generates such URLs (and thus throws errors with IPv6 literals) probably doesn't need to generate that URL at all.

There are two main issues causing errors when `GRIST_HOST` is set to an IPv6 literal like `::`. 

FlexServer.ts line 276, `getOwnUrl()`. This function places the value of `GRIST_HOST` directly into a URL-looking string but can return a string containing an invalid URL. Also `GRIST_HOST` is not validated at any point to ensure it can be used like this. This function gets called if either `APP_UNTRUSTED_URL` or `APP_HOME_URL` are unset. It also appears to be called if `APP_DOC_URL` is unset, but I haven't run into where that is used yet.

```
...
public getOwnUrl(): string {
    const port = this.getOwnPort();
    return `http://${this.host}:${port}`;
}
...
```

gristUrls.ts line 613 in `parseSubdomain`. This function extracts the first group of characters preceding the first `.` in the value of the parameter "host". This is called from getOrgFromHost() in the same file and the value of "host" is from the client request's `Host` header.

```
...
  const match = /^([^.]+)(\..+\..+)$/.exec(host.toLowerCase());
  if (match) {
    const org = match[1];
    const base = match[2];
    if (subdomainRegex.exec(org)) {
      return {org, base};
    }
...
```

This works fine with DNS domain names, and IPv4 literals since they contain dots. However with IPv6 literals such as `[2001:db8::1234]:8484` will result in an `org` part that is invalid in other parts of Grist's code, and will result in errors. As is, the software probably cannot be used at all if accessed via an IPv6 literal URL such as `http://[2001:db8::1234]:8484`, even if the above mentioned environment variables are set.

Finally, `GRIST_UNTRUSTED_PORT` _must_ be set, even though README.md suggests that this does not need to be set if `APP_UNTRUSTED_URL` is set. This looks like a separate bug, but affects IPv6 support because `APP_UNTRUSTED_URL` must be set.  

server.ts line 120 sets `GRIST_UNTRUSTED_PORT` to `0` if it was otherwise unset.  Then mergedServerMain.ts line 36 checks `process.env.GRIST_UNTRUSTED_PORT` for truthiness, which is true for a string containing the character `0`. Ultimately this results in checkUserContentPort() skipping all parsing of `APP_UNTRUSTED_URL`, and the plugin HTTP server starting on an ephemeral port regardless of the port specified in `APP_UNTRUSTED_URL`. So, both must be set explicitly and to the same value.
