### ISSUE TITLE
Cannot import document anymore (main branch, local instance)

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#661]
## Edit

I have found a way to solve my issue. See my last comment.

Still wondering if that's what I was supposed to do to solve the issue.

## Context

As a developer, there is a document that I cannot import anymore using a local instance of Grist (setup for my developments). The error is given below.

I could not figure out why this document particularly fails to be loaded. I can only say it uses various column types, formulas, and is quite heavy. 

Other documents (simpler ones, even with formulas) work.

Also I could bisect and found what commit introduce my issue: https://github.com/gristlabs/grist-core/commit/b9adcefcce99d3d4f5ab7f129664165a28a55a33

I don't know if I am missing something. If you have an idea of the cause of the issue, I would be grateful. Otherwise I continue to try to identify what particularly in this document causes the issue.

Also I can provide you privately the document mentioned in the logs.

```
2023-09-05 15:22:22.301 - info: Sandbox stderr: [INFO] [__main__] Ready sandboxPid=395440, flavor=unsandboxed, command=undefined, entryPoint=(default), docId=fmnFs6xbbSTgNvej5H4YyR
2023-09-05 15:22:22.302 - info: Sandbox stderr: [WARNING] [sandbox] Call error in load_meta_tables: Traceback (most recent call last):
  File "/home/florentpro/projects/grist-core/sandbox/grist/sandbox.py", line 147, in run
    ret = self._functions[fname](*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/main.py", line 70, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/main.py", line 113, in load_meta_tables
    return eng.load_meta_tables(load_and_record_table_data("_grist_Tables", meta_tables),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/engine.py", line 319, in load_meta_tables
    self.rebuild_usercode()
  File "/home/florentpro/projects/grist-core/sandbox/grist/engine.py", line 1118, in rebuild_usercode
    self.gencode.make_module(self.schema)
  File "/home/florentpro/projects/grist-core/sandbox/grist/gencode.py", line 176, in make_module
    fullparts.append(self._make_table_model(table_info, summary_tables.get(table_info.tableId)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/gencode.py", line 144, in _make_table_model
    parts.append(indent(self._make_field(col_info, table_id)))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/gencode.py", line 124, in _make_field
    return self._make_data_field(col_info, table_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/gencode.py", line 110, in _make_data_field
    parts.append(self._make_formula_field(col_info, table_id,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/gencode.py", line 97, in _make_formula_field
    body = codebuilder.make_formula_body(col_info.formula, default, assoc_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/codebuilder.py", line 63, in make_formula_body
    atok = asttokens.ASTText(tmp_formula.get_text(), filename=code_filename)
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'asttokens' has no attribute 'ASTText'
 sandboxPid=395440, flavor=unsandboxed, command=undefined, entryPoint=(default), docId=fmnFs6xbbSTgNvej5H4YyR
2023-09-05 15:22:22.303 - debug: Sandbox pyCall[load_meta_tables] took 247 ms sandboxPid=395440, flavor=unsandboxed, command=undefined, entryPoint=(default), docId=fmnFs6xbbSTgNvej5H4YyR
2023-09-05 15:22:22.305 - warn: ActiveDoc _finishInitialization stopped with SandboxError: [Sandbox] AttributeError module 'asttokens' has no attribute 'ASTText'
    at NSandbox._pyCallWait (/home/florentpro/projects/grist-core/_build/app/server/lib/NSandbox.js:242:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NSandbox.pyCall (/home/florentpro/projects/grist-core/_build/app/server/lib/NSandbox.js:150:20)
    at async ActiveDoc._rawPyCall (/home/florentpro/projects/grist-core/_build/app/server/lib/ActiveDoc.js:2243:20)
    at async TableMetadataLoader.opCorePush (/home/florentpro/projects/grist-core/_build/app/server/lib/TableMetadataLoader.js:121:9)
    at async TableMetadataLoader._counted (/home/florentpro/projects/grist-core/_build/app/server/lib/TableMetadataLoader.js:186:20)
    at async TableMetadataLoader.wait (/home/florentpro/projects/grist-core/_build/app/server/lib/TableMetadataLoader.js:100:13)
    at async ActiveDoc._finishInitialization (/home/florentpro/projects/grist-core/_build/app/server/lib/ActiveDoc.js:2001:13)
    at async InactivityTimer.disableUntilFinish (/home/florentpro/projects/grist-core/_build/app/common/InactivityTimer.js:76:20) access=owners, userId=5, email=you@example.com, age=0, org=docs, altS
essionId=9tez1aE6YshUpsG5unUUe3, clientId=7b29611c043a530b, counter=55, docId=fmnFs6xbbSTgNvej5H4YyR
2023-09-05 15:22:22.322 - info: Client onMessage b'{"reqId":1,"method":"fetchTable","args":[0,"Fabriques_territoire"]}' email=you@example.com, userId=5, age=0, org=docs, altSessionId=9tez1aE6YshUpsG5
unUUe3, clientId=7b29611c043a530b, counter=55
2023-09-05 15:22:22.323 - debug: activeDocMethod access=owners, userId=5, email=you@example.com, age=0, org=docs, altSessionId=9tez1aE6YshUpsG5unUUe3, clientId=7b29611c043a530b, counter=55, docId=fmn
Fs6xbbSTgNvej5H4YyR, docMethod=fetchTable
2023-09-05 15:22:22.323 - info: ActiveDoc fetchQuery {"tableId":"Fabriques_territoire","filters":{}} (regular) access=owners, userId=5, email=you@example.com, age=0, org=docs, altSessionId=9tez1aE6Ys
hUpsG5unUUe3, clientId=7b29611c043a530b, counter=55, docId=fmnFs6xbbSTgNvej5H4YyR
2023-09-05 15:22:22.324 - info: Sandbox stderr: [WARNING] [sandbox] Call error in fetch_table: Traceback (most recent call last):
  File "/home/florentpro/projects/grist-core/sandbox/grist/sandbox.py", line 147, in run
    ret = self._functions[fname](*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/main.py", line 70, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/main.py", line 92, in fetch_table
    return actions.get_action_repr(eng.fetch_table(table_id, formulas=formulas, query=query))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florentpro/projects/grist-core/sandbox/grist/engine.py", line 386, in fetch_table
    table = self.tables[table_id]
            ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'Fabriques_territoire'
 sandboxPid=395440, flavor=unsandboxed, command=undefined, entryPoint=(default), docId=fmnFs6xbbSTgNvej5H4YyR
2023-09-05 15:22:22.325 - debug: Sandbox pyCall[fetch_table] took 1 ms sandboxPid=395440, flavor=unsandboxed, command=undefined, entryPoint=(default), docId=fmnFs6xbbSTgNvej5H4YyR
2023-09-05 15:22:22.325 - warn: Client Responding to method fetchTable with error: Error: [Sandbox] KeyError 'Fabriques_territoire'
    at NSandbox._pyCallWait (/home/florentpro/projects/grist-core/_build/app/server/lib/NSandbox.js:242:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NSandbox.pyCall (/home/florentpro/projects/grist-core/_build/app/server/lib/NSandbox.js:150:20)
    at async ActiveDoc._rawPyCall (/home/florentpro/projects/grist-core/_build/app/server/lib/ActiveDoc.js:2243:20)  email=you@example.com, userId=5, age=0, org=docs, altSessionId=9tez1aE6YshUpsG5unU
Ue3, clientId=7b29611c043a530b, counter=55
```

**Comment by fflorent** [comment]
NB: I made `yarn install:python` before starting the server, with no luck.

**Comment by fflorent** [comment]
Alright, I could solve the issue by removing the `./sandbox_venv3` directory and doing `yarn install:python`.

Is this the way to go to upgrade modules? In such a case, you can close the issue :).

**Comment by paulfitz** [comment]
I've also run into this, and it took me a while to figure out that deleting sandbox_venv3 was the trick.

Maybe it would suffice to just not have `buildtools/prepare_python3.sh` declare success if the directory exists, but continue on to do an install? There is a wrinkle in that script related to electron builds though.
