### ISSUE TITLE
Grist-electron pyodide fatal error. Is there a way to debug this?

### ISSUE THREAD

**Issue by Skefflock** [gristlabs/grist-core#678]
Hello.

I've got this error.

I've searched over the Internet, then here on github with no result on this message or even anything alike.

>  ERROR: Error: [Sandbox] PipeToSandbox is closed: [pyodide error] RangeError: Maximum call stack size exceeded
    at wasm://wasm/02239a6e:wasm-function[3174]:0x25deab
    at wasm://wasm/02239a6e:wasm-function[3175]:0x26a9f5
    at wasm://wasm/02239a6e:wasm-function[1045]:0x1a0038
    at wasm://wasm/02239a6e:wasm-function[1059]:0x1a0d44
    at wasm://wasm/02239a6e:wasm-function[1061]:0x1a0eba
    at wasm://wasm/02239a6e:wasm-function[2490]:0x1fdbb7
    at wasm://wasm/02239a6e:wasm-function[2095]:0x1e40d3
    at wasm://wasm/02239a6e:wasm-function[2094]:0x1e3e84
    at wasm://wasm/02239a6e:wasm-function[2101]:0x1e4475
    at wasm://wasm/02239a6e:wasm-function[3174]:0x2699af {
    pyodide_fatal_error: true
    }

    at y._onServerMessage (http://localhost:47478/v/unknown/main.bundle.js:2:17445)
    at b (http://localhost:47478/v/unknown/main.bundle.js:2:728334)
    at g (http://localhost:47478/v/unknown/main.bundle.js:2:728126)
    at d (http://localhost:47478/v/unknown/main.bundle.js:2:726079)
    at c.trigger (http://localhost:47478/v/unknown/main.bundle.js:2:728019)
    at m._processReceivedMessage (http://localhost:47478/v/unknown/main.bundle.js:2:11017)
    at m.onmessage (http://localhost:47478/v/unknown/main.bundle.js:2:9634)

I use grist-electron v0.2.6. Last version that has a build for mac-intel.

Don't know what is the reason of it so have no clue of how to reproduce. The error shows occasionally. Looks like mostly when I try to change something in db structure. For example when I try to add a column or rename a column. And after first occasion it shows almost on any action.

In the document I have 11 tables with less than 3000 rows totally. A bit of python for some trigger fields. And this error message.

Is there a way to find what triggers this. Debug it or so? Developer console shows exactly what I see in pop up message with no additional information.

**Comment by paulfitz** [comment]
`Maximum call stack size exceeded` sounds like a formula problem, with something calling itself a lot, is that possible? If your formulas are not sensitive, then the content of Code View for your document could be revealing.

Or there could be a problem specifically with the "pyodide" sandbox used to run formulas. If you know your way around with environment variables, it is possible to turn it off, as described here (the `GRIST_SANDBOX_FLAVOR` bit):
https://github.com/gristlabs/grist-electron#configure
Formulas will then run directly on a version of python included with Grist. You could still well still see the error, it would just add more evidence that there's some loop in a formula somewhere, or an odd circular dependency (Grist should really have detected that though and given an error).

**Comment by Skefflock** [comment]
My python script isn't a secret. And sure it calling a lot of unnecessary stuff. Here's the code:

`import re

works = Work_hours.lookupRecords(employee_id=$employee_id)

work_hours = 0
payroll_sum = 0
pay_sum = 0
work_status = 0

for work in works:
  work_status = re.findall("[0-9]+", work.work_id.status)
  work_status = (0 if work_status == [] else int(work_status[0]))
  if (work.hours and work_status < 6):
    work_hours += work.hours
    payroll_sum += (work.ppd if work.ppd else work.pph * work.hours)


pays = AccountDetail.lookupRecords(employee_id=$employee_id, project_id=$project_id)
for pay in pays:
  work_status = re.findall("[0-9]+", pay.work_id.status)
  work_status = (0 if work_status == [] else int(work_status[0]))
  if work_status < 6:
    pay_sum += pay.sum


return ("H/w: " + str(work_hours)
+ "\n PR: " + str(payroll_sum) 
+ "\n P: " + str(pay_sum)
+ "\n C: " + str(payroll_sum + pay_sum)
)`

I understand the realization is totally awful. I call all this and fetch two whole tables for each row. But I've found no other way. All the data I need could be easily extracted from db in one sql query. Even the regex part could be just LIKE clause. Unfortunately I couldn't find any way to run arbitrary sql code. I know there's a lot of risks in client-server model, and also know you already working on this. But still there's no workaround even on local machine. I can run sql query from console on every data set but this is too long and unelegant way.

I've tried to reach the point using custom widget and widget-api and couldn't get the realization idea. There's a getTable(tableId?) function which has no filtering onboard. So still I have to fetch 2 whole tables on every run on each row selection change. Probably there's a way of some optimization in calling for two necessary tables only once on widget load and then make all necessary filtering and calculation in place, but what if source data changes? And in my table AccountDetail there's only 5% of data relative to this calculations still I have no reason to fetch it all.

I may misunderstand some ideas behind the api. I'm not a professional programmer just trying to ease some routine in my life.

**Comment by Skefflock** [comment]
I've just realized that getTable() returns not data but just an interface. CRUD interface with no R. Is there a legal way to read information from DB? I can't see any.

**Comment by paulfitz** [comment]
Hi @Skefflock, thanks for the code. Where does it live? The thing I'm trying to check is if there are any cycles. Is it in a cell in an Employee table? If so it looks reasonable to me. Are there any other formulas lurking around, e.g. trigger formulas?

At this stage it feels like a problem with Grist. Any change you could pare your document down to the essentials to replicate the problem, and share it? I know it is a lot of work.

For custom widgets, you are right, `getTable` doesn't do read yet (for no particular reason, just no-one has implemented it yet). There is a separate function that could be used for that:
https://support.getgrist.com/code/interfaces/grist_plugin_api.GristDocAPI/#fetchtable
Sorry the lack of polish.

There is also more SQL support on the way - there is an endpoint for it https://github.com/gristlabs/grist-core/pull/641 but it isn't document yet and isn't ready to be used from custom widgets.

**Comment by Skefflock** [comment]
@paulfitz thanks for answers. You have nothing to be sorry for. Grist is a wonderful piece of software. Thanks for your work. I'm totally happy with it. Just had to go a bit deeper in programming to get what I need than I was ready for.

The code I've posted did live in a cell in Employee table but does not any more, since I wasn't able to find out why it ruined everything. There are a tiny blocks of code in trigger formulas here and there, but mostly for formatting something based on the same table, nothing than should cause an infinite cycle.

I think your experience may help much more than mine, so here's every piece of custom code in file:
1. In AccountDetail table
```
# week_day cell
import datetime
day_name=['пн','вт','ср','чт','пт','сб','вс']
return day_name[$date.weekday()]
```
```
# category cell
lookup = Voc.lookupOne(description=$description)
if lookup :
  return lookup.category_id or None
else :
  return None
```
```
# partner_id cell
lookup = Voc.lookupOne(description=$description)
if lookup :
  return lookup.partner_id or None
else :
  return None
```
```
# employee_id cell
lookup = Voc.lookupOne(description=$description)
if lookup :
  return lookup.employee_id or None
else :
  return None
```
```
# project_id cell
lookup = Voc.lookupOne(description=$description)
if lookup :
  return lookup.project_id or None
else :
  return None
```

2. In Project table
```
#archive cell
return (True if $date_end else False)
```
```
#show_name cell
return (("✅ "+$name) if $archive else $name)
```

3. Employee table
```
# archive cell
if $date_end : 
  return True
else:
  return False
```
```
# active_name cell
if ($date_end or $archive) :
  return "❌ " + $name
else :
  return $name
```

That's it. No more custom code.

I should mention I don't need any help with it anymore. But I thought this information may help somehow with developing Grist. 

I've chosen other way with custom widget and fetchTable(). A lot of coding, but I like the result much more. And no useless or temporary information is stored in DB. By now it's everything I need. Just a little place where I can do arbitrary calculation with my data. 
I would prefer widget code could be stored somewhere in DB for file to be more consistent. And an ability to edit widget code inplace.

Thanks again.
