### ISSUE TITLE
When add REDIS_URL env after start have error BrowserSession.js:12

### ISSUE THREAD

**Issue by Vladimir-Va** [gristlabs/grist-core#710]
Hello Grist Team!
More and more use webhook, decided to add Redis
add
`REDIS_URL=redis://password@host:port/N`
after restart container i have cicle reboot and error

```
/grist/_build/app/server/lib/BrowserSession.js:12
    session.alive = Number(session.alive || 0) + 1;
                                   ^
TypeError: Cannot read properties of undefined (reading 'alive')
    at forceSessionChange (/grist/_build/app/server/lib/BrowserSession.js:12:36)
    at /grist/_build/app/server/lib/Authorizer.js:419:49
    at Layer.handle [as handle_request] (/grist/node_modules/express/lib/router/layer.js:95:5)
    at next (/grist/node_modules/express/lib/router/route.js:144:13)
    at noop (/grist/_build/app/server/lib/FlexServer.js:101:34)
    at Layer.handle [as handle_request] (/grist/node_modules/express/lib/router/layer.js:95:5)
    at next (/grist/node_modules/express/lib/router/route.js:144:13)
    at addRequestUser (/grist/_build/app/server/lib/Authorizer.js:381:12)
    at async /grist/_build/app/server/lib/expressWrap.js:14:13
Node.js v18.18.2
```
In redis://password@host:port/N i see added data from grist.

**Comment by Vladimir-Va** [comment]
https://github.com/gristlabs/grist-core/issues/633
