### ISSUE TITLE
`access denied` message when closing Grist doc tour or Help pop-ups

### ISSUE THREAD

**Issue by emanuelegissi** [gristlabs/grist-core#919]
Whenever a user closes the Grist doc tour or Grist help popups:

![WhatsApp Image 2024-03-28 at 14 37 28](https://github.com/gristlabs/grist-core/assets/11455203/37f9b826-f60e-48d6-bd12-ec838f4199bf)

an `access denied` message appears:

![WhatsApp Image 2024-03-28 at 14 37 59](https://github.com/gristlabs/grist-core/assets/11455203/84b7e97d-a0a2-4c19-9d9c-4f95151e3d16)

and I see the following message in the server log:

```
2024-03-28 15:10:47.880 - warn: client error stack=Error: Request to https://grist.ge.dipvvf.it/o/vvf-ge/api/orgs/current failed with status 403:  (access denied)
apps-grist    |     at v (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:510970)
apps-grist    |     at D.request (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:510690)
apps-grist    |     at async b.countPendingRequest (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:509391)
apps-grist    |     at async D.updateOrg (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:583651), message=Request to https://grist.ge.dipvvf.it/o/vvf-ge/api/orgs/current failed with status 403:  (access denied), status=403, userError=access denied, docId=ruCCvretZZGVfbM4S9fTYt, page=https://grist.ge.dipvvf.it/ruCCvretZZGV/Gestione-Comando/p/48, language=it-IT, platform=Linux x86_64, userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36, org=vvf-ge, email=emanuele.gissi@vigilfuoco.it, userId=4, altSessionId=7Af1QrKE3kLQRwRzcS9WLc
```

Going to the offending link gives:

![image](https://github.com/gristlabs/grist-core/assets/11455203/8c9e263e-4df8-4edc-be2d-3d59f71a964f)

Removing `current` gives:

![image](https://github.com/gristlabs/grist-core/assets/11455203/529636fd-1e7a-4dae-8490-3234dd77abd8)

The same happens with any user, even the `owner`.

It seems to me that the preference is not written in the `prefs` table of the `home.sqlite3` file. So the popups keep appearing again and again.

How can I help you debugging?

**Comment by georgegevoian** [comment]
Hi @emanuelegissi. Can you scan the server logs for any errors during the PATCH /orgs/current call? You may need to set `DEBUG=1` or `VERBOSE=1` to increase the logging level. Thanks.

**Comment by emanuelegissi** [comment]
Hi @georgegevoian,
I restarted the grist server, reproduced the issue, and checked the log.

I scanned the log for the PATCH word and I found what follows:

```
apps-grist    | 2024-03-29 07:46:41.016 - debug: Auth[PATCH]: grist.ge.dipvvf.it /orgs/current customHostSession=, method=PATCH, host=grist.ge.dipvvf.it, path=/orgs/current, org=vvf-ge, email=emanuele.gissi@vigilfuoco.it, userId=4, altSessionId=7Af1QrKE3kLQRwRzcS9WLc
apps-grist    | 2024-03-29 07:46:41.042 grist.ge.dipvvf.it PATCH /o/vvf-ge/api/orgs/current 403 36.624 ms - 25
apps-grist    | 2024-03-29 07:46:41.062 - debug: Auth[POST]: grist.ge.dipvvf.it /log customHostSession=, method=POST, host=grist.ge.dipvvf.it, path=/log, org=vvf-ge, email=emanuele.gissi@vigilfuoco.it, userId=4, altSessionId=7Af1QrKE3kLQRwRzcS9WLc
apps-grist    | 2024-03-29 07:46:41.065 - warn: client error stack=Error: Request to https://grist.ge.dipvvf.it/o/vvf-ge/api/orgs/current failed with status 403:  (access denied)
apps-grist    |     at v (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:510970)
apps-grist    |     at D.request (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:510690)
apps-grist    |     at async b.countPendingRequest (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:509391)
apps-grist    |     at async D.updateOrg (https://grist.ge.dipvvf.it/v/unknown/main.bundle.js:2:583651), message=Request to https://grist.ge.dipvvf.it/o/vvf-ge/api/orgs/current failed with status 403:  (access denied), status=403, userError=access denied, docId=ruCCvretZZGVfbM4S9fTYt, page=https://grist.ge.dipvvf.it/ruCCvretZZGV/Gestione-Comando, language=it-IT, platform=Linux x86_64, userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36, org=vvf-ge, email=emanuele.gissi@vigilfuoco.it, userId=4, altSessionId=7Af1QrKE3kLQRwRzcS9WLc
apps-grist    | 2024-03-29 07:46:41.068 grist.ge.dipvvf.it POST /o/vvf-ge/api/log 200 13.319 ms - -
```

I do not see any other PATCH call.
The PATCH call seems issued just before the error appears.

I forgot to say I am using: `image: "docker.io/gristlabs/grist:latest"`

(Thank you!)

**Comment by fflorent** [comment]
What is the result of this SQL query in your `home.sqlite3` DB?
```
select * from acl_rules where id < 10;
```

**Comment by emanuelegissi** [comment]
Here it is:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body>
id | permissions | type | workspace_id | org_id | doc_id | group_id
-- | -- | -- | -- | -- | -- | --
1 | 63 | AclRuleOrg |   | 1 |   | 1
2 | 15 | AclRuleOrg |   | 1 |   | 2
3 | 1 | AclRuleOrg |   | 1 |   | 3
4 | 1 | AclRuleOrg |   | 1 |   | 4
5 | 1 | AclRuleOrg |   | 1 |   | 5
6 | 63 | AclRuleWs | 1 |   |   | 6
7 | 15 | AclRuleWs | 1 |   |   | 7
8 | 1 | AclRuleWs | 1 |   |   | 8
9 | 1 | AclRuleWs | 1 |   |   | 9

</body></html>

**Comment by fflorent** [comment]
Thanks, nothing unusual then.

**Comment by emanuelegissi** [comment]
It seems to me that something strange has happened to the organization or to the workspace.
As if the document was not correctly inserted into the `vvf-ge` organization and the `Home` workspace... 

This is a single organization self-hosting.

**Comment by georgegevoian** [comment]
> It seems to me that something strange has happened to the organization or to the workspace. As if the document was not correctly inserted into the `vvf-ge` organization and the `Home` workspace...
> 
> This is a single organization self-hosting.

Is it affecting all documents on your instance or just this specific one?

**Comment by emanuelegissi** [comment]
Today I inspected my home.sqlite3 db. This is what I found. I have some doubts.

**users** table, the two owners (me!) in bold

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body>
id | name | api_key | picture | first_login_at | is_first_time_user | options | connect_id | ref
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | Anonymous | NULL  | NULL  | 2024-03-25 12:00:29.000 | 0 | NULL  |  NULL | hnh...
2 | Preview | NULL  | NULL  | 2024-03-25 12:00:29.000 | 0 |  NULL |  NULL | b6q...
3 | Everyone | NULL  |  NULL | 2024-03-25 12:00:30.000 | 0 | NULL  |  NULL | 5cm...
4 | **Support** | abcd... |  NULL | 2024-03-25 12:00:30.000 | 0 |  NULL |  NULL | e5r...
5 | **emanuele.gissi@...** | NULL  | NULL  | 2024-03-25 12:00:30.000 | 1 |  NULL | NULL  | ayH...
6 | john.smith | NULL  | NULL  | 2024-03-26 10:49:55.000 | 0 | NULL  |  NULL | g2H...
</body></html>

**orgs** table:
`vvf-ge` is the single organization for this self-hosted Grist instance.
Its `owner_id` field is `NULL`, is this right? or should it be `4` (me)?
Why is `domain` field empty for `org` 4? I expect it to be `NULL`.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body>
id | name | domain | created_at | updated_at | owner_id | billing_account_id | host
-- | -- | -- | -- | -- | -- | -- | --
1 | Personal | NULL  | 2024-03-25 12:00:30 | 2024-03-25 12:00:30.156 | 4 | 1 |  
2 | Personal | NULL  | 2024-03-25 12:00:30 | 2024-03-25 12:00:30.368 | 5 | 2 |  
3 | **vvf-ge** | vvf-ge | 2024-03-25 12:00:30 | 2024-03-25 12:00:30.536 | **NULL**  | 3 |  
4 | Personal |   | 2024-03-26 10:49:55 | 2024-03-26 10:49:55.760 | 6 | 4 |  
5 | Personal | NULL  | 2024-03-28 08:57:29 | 2024-03-28 08:57:29.662 | 7 | 5 |  
6 | Personal |  NULL | 2024-03-28 13:54:32 | 2024-03-28 13:54:32.106 | 8 | 6 |  

</body></html>

**workspaces** table:
Seems ok to me.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body>
id | name | created_at | updated_at | org_id | removed_at
-- | -- | -- | -- | -- | --
1 | Home | 2024-03-25 12:00:30 | 2024-03-25 12:00:30.193 | 1 |  
2 | Home | 2024-03-25 12:00:30 | 2024-03-25 12:00:30.395 | 2 |  
3 | **Home** | 2024-03-25 12:00:30 | 2024-03-25 12:00:30.563 | 3 |  
4 | Home | 2024-03-26 10:49:55 | 2024-03-26 10:49:55.818 | 4 |  
5 | Home | 2024-03-28 08:57:29 | 2024-03-28 08:57:29.718 | 5 |  
6 | Home | 2024-03-28 13:54:32 | 2024-03-28 13:54:32.144 | 6 |  
</body></html>

**orgs** table:
`Gestione Comando` is currently the only document.
Is the following record right? Or should the `Gestione Comando` doc refer to `workspace_id` 3, that is related to `org_id` 3 (`vvf-ge`, the only org)?
according to the UI, it was created in the `home` workspace of the `vvf-ge` org.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body>
id | name | created_at | updated_at | workspace_id | is_pinned | url_id | removed_at | options | grace_period_start | usage | created_by | trunk_id | type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ruCCvre... | **Gestione Comando** | 2024-03-25 15:02:25 | 2024-04-02 01:00:04.447 | 1 | 0 | ruCCvre... |   |   |   | {"rowCount":{"1":39,"2":779,...},"dataSizeBytes":...,"attachmentsSizeBytes":...} | 4 |   |  
</body></html>

**prefs** table:
Is this right? or should the `org_id` refer to the `org` 3 (`vvf-ge`, the only org) instead of `NULL`?
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body>
org_id | user_id | prefs
-- | -- | --
1 | 4 | {"showGristTour":true}
2 | 5 | {"showGristTour":true}
NULL | 4 | {"showNewUserQuestions":true,"recordSignUpEvent":true}
4 | 6 | {"showGristTour":true}
NULL  | 6 | {"showNewUserQuestions":true,"recordSignUpEvent":true}
5 | 7 | {"showGristTour":true}
NULL  | 7 | {"showNewUserQuestions":true,"recordSignUpEvent":true}
6 | 8 | {"showGristTour":true}
NULL  | 8 | {"showNewUserQuestions":true,"recordSignUpEvent":true}
7 | 9 | {"showGristTour":true}
NULL  | 9 | {"showNewUserQuestions":true,"recordSignUpEvent":true}
8 | 10 | {"showGristTour":true}
NULL  | 10 | {"showNewUserQuestions":true,"recordSignUpEvent":true}
9 | 11 | {"showGristTour":true}
NULL  | 11 | {"showNewUserQuestions":true,"recordSignUpEvent":true}
</body></html>

Shall I look elsewhere?

**Comment by emanuelegissi** [comment]
Today I created a new document. The `access denied` message appears as well in the new document.
Next attempt is going to be a total reset of the home db.

**Comment by emanuelegissi** [comment]
Well, I "fixed" the issue. I restarted my environment from scratch, and imported the previous `Gestione Comando` document.

Then I opened the new `home.sqlite3` file and checked the differences with the previous one.

It seems that the problem was that the old `Gestione Comando` doc referred to the wrong `workspace_id` number 1, instead of the right one number 3, that is related to  the only existing org `vvf-ge`, as shown in the original tables above.

Why that happened? Hard to say. But I learned a lot on grist docs inner workings ;-)
This issue is probably related to the single org hosting. Is any new doc or imported doc being correctly inserted in the right workspace of the only existing organization?

I will try to reproduce the issue, and report back.

**Comment by emanuelegissi** [comment]
As I was telling you, something strange is happening with single org hosting and workspaces.
Now my Grist is showing two `Home` workgroups:

![image](https://github.com/gristlabs/grist-core/assets/11455203/ac84211f-3be2-44e1-9779-691a76187554)

The first one should be the `Home` for the `vvf-ge` organisation.
The second one is my personal home, so I renamed it `Personal home`.
