### ISSUE TITLE
gvisor sandbox fails when container storage on XFS: `OSError: [Errno 38] Function not implemented`

### ISSUE THREAD

**Issue by gabriel-v** [gristlabs/grist-core#922]
After unrelated https://github.com/gristlabs/grist-core/issues/914 I ran into this following error:

```
2024-04-01 14:42:31.591 - debug: 3-pipe Sandbox started sandboxPid=69, flavor=gvisor, command=undefined, entryPoint=(default)
2024-04-01 14:42:31.630 - info: Sandbox stderr: run.py: sandbox/gvisor/run.py -E PYTHONPATH=/grist/sandbox/grist -E PIPE_MODE=minimal -m /grist/sandbox --checkpoint /tmp/engine__grist python3 -- /grist/sandbox/grist/main.py sandboxPid=69, flavor=gvisor, command=undefined, entryPoint=(default)
2024-04-01 14:42:31.889 - info: Sandbox stderr: Problem: Traceback (most recent call last): sandboxPid=69, flavor=gvisor, command=undefined, entryPoint=(default)
2024-04-01 14:42:31.890 - info: Sandbox stderr: Problem:   File "/grist/sandbox/grist/main.py", line 11, in <module> sandboxPid=69, flavor=gvisor, command=undefined, entryPoint=(default)
2024-04-01 14:42:31.890 - info: Sandbox stderr: Problem:     import logging sandboxPid=69, flavor=gvisor, command=undefined, entryPoint=(default)
2024-04-01 14:42:31.891 - info: Sandbox stderr: Problem:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
Problem:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
Problem:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Problem:   File "<frozen importlib._bootstrap_external>", line 936, in exec_module
Problem:   File "<frozen importlib._bootstrap_external>", line 1073, in get_code
Problem:   File "<frozen importlib._bootstrap_external>", line 1131, in get_data sandboxPid=69, flavor=gvisor, command=undefined, entryPoint=(default)
2024-04-01 14:42:31.891 - info: Sandbox stderr: Problem: OSError: [Errno 38] Function not implemented sandboxPid=69, flavor=gvisor, command=undefined, entryPoint=(default)
```

The source of the problem seems to be the XFS filesystem that the volume data is mounted on. 

Is XFS known to be unsupported with gVisor?

**Comment by paulfitz** [comment]
Hmm searching for [XFS on gvisor repo](https://github.com/search?q=repo%3Agoogle%2Fgvisor+xfs&type=issues) brings up issues with various random problems that get resolved, where people happen to be using XFS but that isn't the problem, so I would tentatively guess that XFS can work.

Not very sure how to debug. Could check what `File "<frozen importlib._bootstrap_external>", line 1131, in get_data` for the given version of `importlib` is doing?

**Comment by gabriel-v** [comment]
Ah good idea. In the container:

```
# find / -name '_bootstrap_external.py'
/usr/local/lib/python3.11/importlib/_bootstrap_external.py
# python3 --version
Python 3.11.4
```

The [file on github](https://github.com/python/cpython/blob/v3.11.4/Lib/importlib/_bootstrap_external.py#L1131) is identical to the file at the path above.

The failing operation is `f.read()` where f was opened with `_io.open_code(...)`.

The `_io.open_code` function is implemented in C here: https://github.com/python/cpython/blob/v3.11.4/Modules/_io/clinic/_iomodule.c.h#L329-L358 -- through that's not very helpful since it calls opaque fnpointer `_io_open_code_impl`


I will try to get the runsc arguments `--strace --debug` into the command that runs the sandbox, [as per gvisor docs](https://gvisor.dev/docs/user_guide/debugging/). Is there some env var that I can override to add these arguments everywhere, or do I need to fork and add them manually?

Thanks!

**Comment by gabriel-v** [comment]
Running:

```
docker run -it --rm --privileged --name grist_debug -v /storage/_grist_debug:/persist  --cap-add=SYS_PTRACE -e GVISOR_FLAGS='-unprivileged -ignore-cgroups --debug --strace --debug-log=/persist/gvisor-debug.log' -e 'GRIST_SANDBOX_FLAVOR=gvisor' gristlabs/grist:1.1.12
```

Where `/storage` is XFS.

Log output is same as above.

Runsc output with and without `--strace`: https://gist.github.com/gabriel-v/fbfbe486487ca6c4d3ea20629ccf7575

**Comment by paulfitz** [comment]
Hmmm one thing I remember running into was a limit on number of open files. Don't know if symptom would be exactly what you are seeing though. I see on our SaaS that we have the following setting:
```
      ulimits:
        - name: nofile
          softLimit: 65535
          hardLimit: 65535
```
Could be good to just double-check there is no file-related `ulimit` being hit.

**Comment by gabriel-v** [comment]
Set the `nofile` limit to 65k, both on host users and on container config, same error

Set SELINUX=disabled on host, same error

We will obtain some ext4 volumes on those same machines and mount on those instead of XFS, to see if sandbox will work then

**Comment by paulfitz** [comment]
@gabriel-v there's a pyodide sandbox, used for desktop app and grist-static, it needs a little setup that isn't in the standard image: https://github.com/gristlabs/grist-core/tree/main/sandbox/pyodide

There are a few other sandboxes, and it is relatively easy to add more:
https://github.com/gristlabs/grist-core/blob/513e13e6ab57c918c0e396b1d56686e45644ee1a/app/server/lib/NSandbox.ts#L461-L469

PRs welcome in this area. At Grist Labs all our development efforts are currently focused elsewhere unfortunately.
