### ISSUE TITLE
OIDC issuer behind a proxy cannot be accessed

### ISSUE THREAD

**Issue by gautierrog** [gristlabs/grist-core#942]
Hello,

Self hosting grist with docker here. I have an OIDC issuer which can only be accessed through a proxy.

I pass the following environment variables on my container:

- HTTP_PROXY
- HTTPS_PROXY
- http_proxy
- https_proxy
- NO_PROXY
- no_proxy

However, issuer is still unreachable:

```
RPError: outgoing request timed out after 3500ms
    at /grist/node_modules/openid-client/lib/helpers/request.js:137:13
    at async Issuer.discover (/grist/node_modules/openid-client/lib/issuer.js:171:22)
    at async OIDCConfig.initOIDC (/grist/_build/app/server/lib/OIDCConfig.js:100:24)
    at async Object.getMiddleware (/grist/_build/app/server/lib/OIDCConfig.js:229:13)
    at async FlexServer.loadConfig (/grist/_build/app/server/lib/FlexServer.js:1093:33)
    at async main (/grist/_build/app/server/mergedServerMain.js:83:5)
    at async main (/grist/_build/stubs/app/server/server.js:144:20)
```

I did not find any documentation telling how to setup a proxy for grist server. What would be the solution ?

**Comment by plimptm** [comment]
I just had the exact same error reported here in my instance which is also behind a (corporate) forward proxy.

I was suspicious that the environment variables were not being utilized so I set `NODE_DEBUG=https` and confirmed that the outgoing connection to my OIDC IDP issuer is not using the proxy which has been set.

**Comment by paulfitz** [comment]
Node has been a bit of an outlier in terms of support for proxy variables. Since https://github.com/nodejs/undici/pull/2994 (undici is what node uses for its native fetch implementation) that may be changing. In the meantime, there is a `proxyAgent(url)` method in `app/server/lib/ProxyAgent.ts` that can give an agent consistent with other parts of Grist. @fflorent what do you think of telling `openid-client` about that in the way @plimptm suggests?

**Comment by fflorent** [comment]
> Since https://github.com/nodejs/undici/pull/2994 (undici is what node uses for its native fetch implementation) that may be changing.

Unfortunately, `node-openid-client` uses directly the `http` / `https` native module: https://nodejs.org/api/http.html

> @fflorent what do you think of telling openid-client about that in the way @plimptm suggests?

That should be pretty much doable, and not very difficult. The harder would be to setup an environment for testing manually (or even better but even harder: setting up an integration test in the CI), that's the reason why I would not flag it `good-first-issue`.

**Comment by plimptm** [comment]
@fflorent I'm more than willing to help with testing code changes, both using my existing environment and hopefully coming up with a similar test environment.
